using System.IO.Compression;
using System.Text.Json;

namespace Nexa.Services.Logging;

/// <summary>Writes a small allowlisted diagnostic archive without arbitrary log text or files.</summary>
public static class DiagnosticBundle
{
    public const int MaximumMods = 4096;
    public const int MaximumLogs = 2000;
    public const int MaximumBytes = 2 * 1024 * 1024;

    public static Task WriteAsync(string destination, DiagnosticBundleSnapshot snapshot, CancellationToken token = default) =>
        Task.Run(() => Write(destination, snapshot, token), token);

    private static void Write(string destination, DiagnosticBundleSnapshot snapshot, CancellationToken token)
    {
        ArgumentNullException.ThrowIfNull(snapshot);
        if (!Path.IsPathFullyQualified(destination)) throw new ArgumentException("Choose an absolute export destination.", nameof(destination));
        string target = Path.GetFullPath(destination);
        string temporary = Path.Combine(Path.GetDirectoryName(target)!, ".nexa-diagnostic-" + Guid.NewGuid().ToString("N") + ".tmp");
        bool created = false;
        long uncompressedBytes = 0;
        try
        {
            token.ThrowIfCancellationRequested();
            using (FileStream file = new(temporary, FileMode.CreateNew, FileAccess.ReadWrite, FileShare.None))
            {
                created = true;
                using (ZipArchive archive = new(file, ZipArchiveMode.Create, leaveOpen: true))
                {
                    Entry("summary.json", json =>
                    {
                        json.WriteNumber("schema", 1);
                        json.WriteString("nexa_version", Safe(snapshot.NexaVersion));
                        json.WriteString("os", Safe(snapshot.OperatingSystem));
                        json.WriteString("arch", Safe(snapshot.Architecture));
                        NullableNumber(json, "java_major", snapshot.JavaMajor);
                        json.WriteString("minecraft", Safe(snapshot.MinecraftVersion));
                        json.WriteString("loader", Safe(snapshot.Loader));
                        json.WriteString("crash_classification", Safe(snapshot.CrashClassification));
                        NullableNumber(json, "integrity_verified_files", snapshot.IntegrityVerifiedFiles);
                        NullableNumber(json, "integrity_failed_files", snapshot.IntegrityFailedFiles);
                        NullableNumber(json, "failed_tasks", snapshot.FailedTasks);
                        if (snapshot.InventoryComplete is { } complete) json.WriteBoolean("inventory_complete", complete);
                        else json.WriteNull("inventory_complete");
                        json.WriteBoolean("mods_truncated", snapshot.Mods.Count > MaximumMods);
                        json.WriteBoolean("logs_truncated", snapshot.Logs.Count > MaximumLogs);
                        json.WriteString("log_policy", "structured-operation-only; messages/exceptions/context excluded");
                        json.WriteStartArray("preflight_codes");
                        foreach (string code in snapshot.PreflightIssueCodes.Take(128)) json.WriteStringValue(Safe(code));
                        json.WriteEndArray();
                    });
                    Entry("mods.json", json =>
                    {
                        json.WriteStartArray("mods");
                        foreach (DiagnosticModIdentity mod in snapshot.Mods.Take(MaximumMods))
                        {
                            token.ThrowIfCancellationRequested();
                            json.WriteStartObject();
                            json.WriteString("id", Safe(mod.Id));
                            json.WriteString("version", Safe(mod.Version));
                            json.WriteBoolean("enabled", mod.Enabled);
                            json.WriteEndObject();
                        }
                        json.WriteEndArray();
                    });
                    Entry("logs.json", json =>
                    {
                        json.WriteStartArray("operations");
                        foreach (LogEntry entry in snapshot.Logs.TakeLast(MaximumLogs))
                        {
                            token.ThrowIfCancellationRequested();
                            json.WriteStartObject();
                            json.WriteString("timestamp", entry.Timestamp);
                            json.WriteString("level", Enum.IsDefined(entry.Level) ? entry.Level.ToString() : "unknown");
                            // Module names are generated by our code, but reject malformed identifiers anyway.
                            json.WriteString("module", Safe(entry.Module));
                            if (entry.Operation is { } operation)
                            {
                                json.WriteString("operation", Safe(operation.Name));
                                json.WriteString("stage", Safe(operation.Stage));
                                json.WriteString("outcome", Enum.IsDefined(operation.Outcome) ? operation.Outcome.ToString() : "unknown");
                            }
                            // Raw text can contain unlabeled passwords/accounts/paths; it is NEVER copied.
                            json.WriteEndObject();
                        }
                        json.WriteEndArray();
                    });

                    void Entry(string name, Action<Utf8JsonWriter> body)
                    {
                        token.ThrowIfCancellationRequested();
                        using MemoryStream buffer = new();
                        using (Utf8JsonWriter json = new(buffer))
                        {
                            json.WriteStartObject();
                            body(json);
                            json.WriteEndObject();
                        }
                        uncompressedBytes += buffer.Length;
                        if (uncompressedBytes > MaximumBytes) throw new InvalidDataException("Diagnostic content exceeds budget.");
                        buffer.Position = 0;
                        using Stream stream = archive.CreateEntry(name, CompressionLevel.Fastest).Open();
                        buffer.CopyTo(stream);
                    }
                }
                if (file.Length > MaximumBytes) throw new InvalidDataException("Diagnostic archive exceeds budget.");
                file.Flush(true);
            }
            token.ThrowIfCancellationRequested();
            File.Move(temporary, target, overwrite: false);
            created = false;
        }
        finally
        {
            if (created) File.Delete(temporary);
        }
    }

    private static string? Safe(string? value)
    {
        if (value is null) return null;
        if (value.Length is 0 or > 128 || value.Any(c => !(char.IsAsciiLetterOrDigit(c) || c is '.' or '_' or '-' or '+' or ' '))) return "unknown";
        return value;
    }

    private static void NullableNumber(Utf8JsonWriter json, string name, int? value)
    {
        if (value is >= 0) json.WriteNumber(name, value.Value); else json.WriteNull(name);
    }
}
