namespace Nexa.Services.Tests;

internal static partial class Program
{
    private static readonly (string Name, Func<ValueTask> Body)[] TestCases =
    [
        ("Linux display projects active outputs and explicit primary", Sync(LinuxDisplayProjectsActiveOutputsAndExplicitPrimary)),
        ("macOS power preserves unavailable evidence and battery units", Sync(MacPowerProjectionPreservesUnavailableAndBatteryUnits)),
        ("Linux power enumerates batteries and weights energy", Sync(LinuxPowerEnumeratesSystemBatteriesAndWeightsEnergy)),
        ("Unix GPU budgets do not substitute static capacity", Sync(DedicatedGpuBudgetDoesNotUseStaticCapacityOnUnix)),
        ("Linux display query bounds timeout and cancellation", LinuxDisplayQueryHonorsBoundsTimeoutAndCancellation),
        ("form factor failed probes preserve unknown evidence", FormFactorFailedProbesPreserveUnknown),
        ("Windows power projection recognizes unknown sentinels", Sync(WindowsPowerProjectionRecognizesUnknownSentinels)),
        ("Windows embedded displays preserve unknown evidence", Sync(WindowsDisplayEmbeddedConnectorsPreserveUnknown)),
        ("Microsoft wardrobe validates bytes and owned capes", WardrobeMicrosoftUsesValidatedBytesAndOwnedCapes),
        ("wardrobe rejects unsupported invalid and stale requests", WardrobeRejectsUnsupportedInvalidAndStaleRequests),
        ("wardrobe late responses and failures preserve account", WardrobeLateResponsesAndFailuresPreserveCurrentAccount),
        ("LittleSkin wardrobe separates provider and game tokens", WardrobeLittleSkinUsesProviderAndGameTokensAndClearsCape),
        ("wardrobe bounds chunked responses and cape inventories", WardrobeBoundsChunkedResponsesAndCapeInventories),
        ("wardrobe PNG validates complete static skins", Sync(WardrobePngAcceptsCompleteStaticSkins)),
        ("wardrobe PNG rejects malformed and unsupported structures", Sync(WardrobePngRejectsMalformedStructureAndUnsupportedFormats)),
        ("wardrobe PNG rejects invalid and unbounded image data", Sync(WardrobePngRejectsInvalidAndUnboundedImageData)),
        ("appearance preferences retain legacy modes and durable failures", Sync(AppearancePreferencesRetainLegacyModesRestartAndDurableFailures)),
        ("disk logs rotate within physical bounds", DiskLogsRotateWithinPhysicalBounds),
        ("disk retention protects current unrelated files and links", DiskRetentionProtectsCurrentUnrelatedFilesAndLinks),
        ("disk retention enforces archive count and byte ceilings", DiskRetentionEnforcesArchiveCountAndByteCeilings),
        ("disk log policy applies committed changes without rendering", DiskLogPolicyAppliesCommittedChangesWithoutRendering),
        ("disk retention changes do not wait for log publication", DiskRetentionChangesDoNotWaitForLogPublication),
        ("disk log export includes archives and excludes private text", DiskLogExportIncludesArchivedFactsAndExcludesPrivateText),
        ("disk log export bounds history and cleans cancelled reads", DiskLogExportBoundsHistoryAndCleansCancelledDiskRead),
        ("disk log export snapshot survives rotation and pruning", DiskLogExportSnapshotSurvivesConcurrentRotationAndPruning),
        ("disk log export rejects oversized inputs and keeps sink usable", DiskLogExportBudgetRejectionPreservesLiveSink),
        ("launch hooks capture scoped legacy and empty overrides", Sync(LaunchHooksCaptureScopedLegacyAndEmptyOverrides)),
        ("launch wrapper syntax is bounded and path compatible", Sync(LaunchWrapperSyntaxIsBoundedAndPathCompatible)),
        ("launch wrapper preserves private bootstrap transport", LaunchWrapperPreservesPrivateBootstrapTransport),
        ("launch hooks execute in order and own failure cancellation", LaunchHooksExecuteInOrderAndOwnFailureCancellation),
        ("launch hook platform reaps and kills owned commands", LaunchHookPlatformReapsAndKillsOwnedCommands),
        ("launch hook platform kills children after shell exit", LaunchHookPlatformKillsChildrenAfterShellExit),
        ("launch hook platform startup failure kills waited background children", LaunchHookPlatformStartupFailureKillsWaitedBackgroundChildren),
        ("launch hook platform detach retains children and reaps worker", LaunchHookPlatformDetachRetainsChildrenAndReapsWorker),
        ("launch wrapper forwards real private bootstrap and exit", LaunchWrapperRealProcessForwardsPrivateBootstrapAndExit),
        ("managed Java removal preserves external files", ManagedJavaRemovalCommitsOwnershipAndPreservesExternalFiles),
        ("managed Java removal rejects stale ownership receipts", ManagedJavaRemovalRejectsStaleOwnershipReceipts),
        ("managed Java removal rejects changed extra and linked files", ManagedJavaRemovalRejectsChangedExtraAndLinkedFiles),
        ("managed Java removal rolls back persistence and cancellation", ManagedJavaRemovalRollsBackPersistenceAndCancellation),
        ("managed Java removal excludes active uses and installers", ManagedJavaRemovalExcludesActiveUsesAndInstallers),
        ("direct managed Java launch owns use lease until process exit", ManagedJavaDirectLaunchOwnsUseLeaseUntilProcessExit),
        ("bound managed Java lease survives owner release until process exit", ManagedJavaBoundLeaseSurvivesOwnerReleaseUntilProcessExit),
        ("managed Java lease rejects unknown and malformed records", ManagedJavaLeaseRejectsUnknownAndMalformedRecords),
        ("managed Java lease reclaims only proven exited process identities", ManagedJavaLeaseReclaimsOnlyProvenExitedProcessIdentities),
        ("network transport captures preferences and retains active responses", NetworkTransportCapturesCommittedPreferencesAndRetainsActiveResponses),
        ("foundation network preferences reach actual requests and managed Java roots", FoundationNetworkPreferencesReachActualRequestsAndManagedJavaRoots),
        ("bandwidth policy preserves legacy slider and exact values", Sync(BandwidthPolicyPreservesLegacySliderAndExactNewValues)),
        ("consumer catalog requires contracts and keeps future features reserved", Sync(ConsumerCatalogRequiresRealContractsAndKeepsFutureFeaturesReserved)),
        ("network proxy modes and IP preferences preserve trust", NetworkProxyModesAndIpPreferencesPreserveTrust),
        ("DNS over HTTPS bounds records caches and regional fallback", DnsOverHttpsBoundsRecordsCachesAndUsesRegionalFallback),
        ("download bandwidth captures generations and serializes reads", DownloadBandwidthCapturesGenerationsAndSerializesBodyReads),
        ("download engine captures bandwidth and cleans cancellation", DownloadEngineUsesCapturedBandwidthAndCleansUpOnCancellation),
        ("loader and modpack transfers consume retry concurrency settings", LoaderAndModpackTransfersConsumeRetryAndConcurrencySettings),
        ("storage migration queues copies before startup consumers", StorageMigrationQueuesAndCopiesBeforeStartupConsumers),
        ("storage migration rejects stale occupied locked cancelled requests", StorageMigrationRejectsStaleOccupiedLockedAndCancelledRequests),
        ("storage migration preserves source when locator commit fails", StorageMigrationFailedLocatorCommitPreservesSourceAndRetries),
        ("storage cleanup removes only eligible temporaries and successful cards", StorageCleanupOnlyRemovesEligibleTemporariesAndSuccessfulCards),
        ("storage cleanup startup restores interrupted renames", StorageCleanupStartupRestoresInterruptedRenames),
        ("storage interrupted stages retry and published copies cancel safely", StorageInterruptedStagesRetryAndPublishedCopiesCanCancelSafely),
        ("storage cleanup rolls back renames when idle guard changes", StorageCleanupRollsBackRenamesWhenIdleGuardChanges),
        ("storage malformed records and cleanup kinds reject without mutation", StorageMalformedRecordsAndCleanupKindsRejectWithoutMutation),
        ("storage migration rejects installed Java receipts and preserves lifecycle", StorageMigrationRejectsInstalledJavaReceiptsAndPreservesLifecycle),
        ("storage migration rejects root-bound records and preserves external stores", StorageMigrationRejectsRootBoundGameRecordsAndLeavesExternalStoresAlone),
        ("log preferences apply committed state and dispose", Sync(LogPreferencesApplyCommittedStateAndDispose)),
        ("log retention changes never wait for observers", LogRetentionChangesDoNotWaitForObservers),
        ("log preferences retain legacy values and bounds", Sync(LogPreferencesRetainLegacyValuesAndBounds)),
        ("installed batches reuse partial identity and refresh caches", InstalledBatchReusesPartialIdentityAndRefreshesCaches),
        ("explicit resource refresh bypasses merged detail cache", ExplicitResourceRefreshBypassesMergedDetailCache),
        ("update preferences follow build and persist explicit choices", Sync(UpdatePreferencesFollowBuildAndPersistExplicitChoices)),
        ("low power setting retains legacy scope and durability", Sync(LowPowerSettingRetainsLegacyScopeAndDurability)),
        ("Java registration persists and removal keeps files", JavaRegistrationPersistsAndRemovalKeepsFiles),
        ("Java registration failure and late probe never commit", JavaRegistrationFailureAndLateProbeNeverCommit),
        ("Java registration disables automatic and explicit selection", JavaRegistrationDisablesAutomaticAndExplicitSelection),
        ("download settings capture bounded workers and migrate legacy sliders", DownloadSettingsCaptureBoundedWorkers),
        ("download retry settings preserve integrity and commit last", DownloadRetrySettingPreservesIntegrityAndCommitLast),
        ("launch completion uses captured download retry policy", LaunchCompletionUsesDownloadRetryPolicy),
        ("scoped repair setting controls actual preparation and validates server", ScopedRepairSettingControlsActualPreparation),
        ("Java vendor preference remains compatible scoped and durable", JavaVendorPreferenceStaysWithinCompatibility),
        ("game source settings keep authority region and legacy boundaries", Sync(GameSourceSettingsKeepAuthorityAndRegionBoundaries)),
        ("game source settings reach install and launch transfers", GameSourceSettingsReachInstallAndLaunchTransfers),
        ("instance path probes preserve files and isolate concurrent calls", InstancePathProbesPreserveExistingFilesAndIsolateConcurrentCalls),
        ("instance server lists preserve tags and reject stale writes", InstanceServersPreserveUnknownTagsAndRejectStaleWrites),
        ("instance server status uses bounded protocol and admitted revisions", InstanceServerStatusUsesBoundedProtocolAndAdmittedRevision),
        ("instance server lists reject malformed and expanded NBT", InstanceServersRejectMalformedAndExpandedNbtWithoutModification),
        ("instance modpack export round trips selection and protects targets", InstanceModpackExportRoundTripsSelectionAndRetainsExistingTargets),
        ("automatic update differential reconstructs all platforms", AutomaticUpdateDeltaReconstructsAllPlatforms),
        ("automatic update differential failures use authenticated full fallback", AutomaticUpdateDeltaFailureFallsBack),
        ("automatic update differential offline recovery uses active slot", AutomaticUpdateDeltaOfflineRecoveryAndActiveSource),
        ("automatic update differential cancellation never falls back", AutomaticUpdateDeltaCancellationDoesNotDownloadFull),
        ("automatic update native differential transaction", AutomaticUpdateNativeDeltaTransaction),
        ("automatic update recovers every commit boundary offline", AutomaticUpdateRecoversEveryCommitBoundary),
        ("automatic update rejects bytes before activation", AutomaticUpdateRejectsPackageBeforeActivation),
        ("automatic update journal preserves interrupted frames", Sync(AutomaticUpdateJournalPreservesEveryInterruptedFrame)),
        ("automatic update native protected transaction", AutomaticUpdateNativeProtectedTransaction),
        ("automatic update loopback HTTP transaction", AutomaticUpdateLoopbackHttpTransaction),
        ("automatic update differential loopback HTTP transaction", AutomaticUpdateDeltaLoopbackHttpTransaction),
        ("protected update journal rejects rollback and corruption", Sync(UpdateJournalRejectsRollbackAndCorruption)),
        ("protected update journal recovers every interrupted append", Sync(UpdateJournalRecoversEveryInterruptedAppend)),
        ("protected update journal capacity preserves committed records", Sync(UpdateJournalCapacityNeverDiscardsCommittedRecords)),
        ("Windows protected update descriptor policy", Sync(WindowsUpdateDescriptorPolicy)),
        ("Windows protected update read admission", Sync(WindowsUpdateReadAdmission)),
        ("Windows protected update elevated objects", WindowsUpdateElevatedObjects),
        ("Windows protected update high-water object journal", WindowsUpdateProtectedHighWater),
        ("signed release authenticates owned identity and actual package", SignedReleaseAuthenticatesOwnedIdentityAndActualPackage),
        ("signed release rejects routing replay and unordered CI", SignedReleaseRejectsRoutingReplayAndUnorderedCi),
        ("signed release rejects schema aliases and bounds input", SignedReleaseRejectsSchemaAliasesAndBoundsInput),
        ("protected update reception copies verified bytes without source reopening", UpdateReceptionCopiesVerifiedBytesWithoutReopening),
        ("protected update reception rejects actual byte and digest mismatches", UpdateReceptionRejectsActualLengthAndDigest),
        ("protected update reception invalidates cancellation and IO failures", UpdateReceptionInvalidatesCancellationAndIoFailure),
        ("old install trust rejects publication and preserves rollback cancel", OldInstallTrustPreservesRollbackAndRejectsPublication),
        ("Minecraft authority rejects mirror metadata redirects and wrong digest", MinecraftAuthorityRejectsMirrorMetadataAndRedirects),
        ("Minecraft index preserves verified bytes without second transfer", MinecraftIndexUsesVerifiedRawBytesWithoutSecondTransfer),
        ("Forge authority rejects redirect before transfer or execution", ForgeAuthorityRejectsRedirectBeforeInstallerDownload),
        ("update modes strip special and shared write permissions", UpdateModesCannotPropagateSpecialOrSharedWritePermissions),
        ("scheduler telemetry preserves facts while quiet and joins shutdown", TelemetryQuietPreservesQueuedFactsAndJoinsShutdown),
        ("scheduler cancellation races release every lease", WorkCancellationRacesNeverRetainResourceLeases),
        ("scheduler downloads inherit critical and release failure cancellation", ScheduledDownloadsInheritCriticalAndReleaseAfterFailure),
        ("scheduler icons release HTTP before paused CPU decode", ResourceIconsReleaseHttpBeforePausedDecode),
        ("scheduler resource admission is atomic bounded cancellable", WorkAdmissionIsAtomicBoundedAndCancellable),
        ("scheduler optional admission never queues or partially reserves", OptionalWorkAdmissionNeverQueuesOrPartiallyReserves),
        ("recovery capture admission preserves baseline across quiet cancellation", RecoveryCaptureAdmissionPreservesBaselineAcrossQuietCancellation),
        ("recovery maintenance chunks defer and retain journal objects", RecoveryMaintenanceChunksDeferAndRetainJournalObjects),
        ("recovery automatic capture yields to new game operations", AutomaticRecoveryYieldsToNewGameOperations),
        ("recovery source chunks yield when quiet begins mid-file", RecoverySourceChunksYieldWhenQuietBeginsMidFile),
        ("scheduler weights prevent starvation and shutdown drains waiters", WorkAdmissionWeightsPreventStarvationAndDisposeWaiters),
        ("scheduler quiet scopes grace and trusted priority context", WorkQuietScopesRespectGraceAndPriorityContext),
        ("scheduler install prefetch yields and explicit read promotes", InstallPrefetchYieldsAndExplicitReadPromotes),
        ("scheduler update discovery yields and cancels before network", UpdateDiscoveryYieldsAndCancelsWithoutNetwork),
        ("diagnostic bundle excludes private text bounds input and never overwrites", DiagnosticBundleExcludesPersonalTextAndPublishesAtomically),
        ("performance file workers are bounded and join cancellation", FileWorkersAreBoundedAndJoinCancellation),
        ("performance receipts invalidate and explicit verify hashes", FileReceiptsInvalidateAndExplicitVerificationHashes),
        ("performance receipt budget retains recent files and revokes failed hashes", FileReceiptsEvictOnlyLeastRecentlyUsedAndRevokeFailures),
        ("performance snapshot reuses stamps and repairs changed objects", SnapshotReusesStampsAndRepairsChangedObjects),
        ("performance metadata cache retains budget and invalidates stamps", MetadataCacheKeepsBudgetAndInvalidatesFileStamp),
        ("performance logging batches retain ordered bounded state", Sync(BatchedLoggingKeepsBoundedRingAndFlushesState)),
        ("idle logging wakes only for pending batches", Sync(LoggingWakesOnlyForPendingBatches)),
        ("idle file logging is lazy and drains ordered bursts", FileLoggingIsLazyAndDrainsOrderedBursts),
        ("single stream progress is bounded and keeps final bytes", SingleStreamProgressIsBoundedAndKeepsFinalBytes),
        ("Java cache is scoped and rejects invalidated scans", JavaCacheIsScopedAndInvalidationRejectsOldScan),
        ("profile initialization is asynchronous and preserves pending store", ProfileInitializationIsAsyncAndPreservesPendingStore),
        ("profile initialization cancels at shutdown", ProfileInitializationCanBeCancelledAtShutdown),
        ("install draft is service owned and normalizes incompatible addons", Sync(InstallDraftBelongsToServiceAndRejectsIncompatibleAddons)),
        ("international resource transport uses only official", InternationalResourceTransportUsesOnlyOfficial),
        ("regional policy requires verified ownership at every write", Sync(RegionalPolicyRequiresVerifiedOwnershipAtEveryWrite)),
        ("regional policy disables mirrors outside mainland", Sync(RegionalPolicyDisablesMirrorsOutsideMainland)),
        ("language settings are immediate validated and durable", Sync(LanguageSettingIsImmediateValidatedAndDurable)),
        ("region formatting settings validate persist and preserve legacy aliases", Sync(RegionFormattingSettingIsValidatedAndDurable)),
        ("animation frame rate uses actual fps and legacy slider encoding", Sync(AnimationFrameRateUsesActualFpsAndLegacySliderEncoding)),
        ("resource identity malformed providers preserve healthy source and cancellation", ResourceIdentityMalformedProviderPreservesHealthySource),
        ("resource provided aliases retain versions and reject incomplete declarations", ResourceProvidedAliasesKeepVersionsAndRejectIncompleteDeclarations),
        ("resource installed content identifies hashes and rejects stale identity", ResourceInstalledContentUsesHashesAndRejectsStaleIdentity),
        ("resource content batch associates all kinds with batched authority", ResourceContentBatchAssociatesAllKindsWithBatchedAuthority),
        ("installed content updates use exact identities and known chronology", InstalledContentUpdateUsesExactIdentityAndKnownChronology),
        ("resource pack and shader updates retain originals and journal success", ResourcePackAndShaderUpdatesKeepOriginalOnFailureAndJournalSuccess),
        ("resource mod install verifies actual dependency tables before importing", ResourceModInstallationVerifiesActualDependenciesBeforeImport),
        ("resource mod removal preserves shared dependencies and revalidates", ResourceModRemovalPreservesSharedDependenciesAndRevalidates),
        ("mod removal impact traverses aliases cycles and indirect consumers", ModRemovalImpactIncludesIndirectAliasesAndSkipsDisabledConsumers),
        ("resource favorites persist by provider identity", ResourceFavoritesPersistByProviderIdentity),
        ("resource dependencies are compatible ordered and bounded", ResourceDependenciesAreCompatibleOrderedAndBounded),
        ("resource search cache avoids duplicate provider work", ResourceSearchCacheAvoidsDuplicateProviderWork),
        ("resource dual source Chinese identity and partial failure", ResourceDualSourceChineseIdentityAndPartialFailure),
        ("resource mirror fallback protects credentials", ResourceMirrorFallbackDoesNotLeakCredentials),
        ("resource translation validates original", ResourceTranslationRequiresMatchingOriginal),
        ("resource CurseForge filters and file permissions", ResourceCurseForgeMapsFiltersFilesAndDeniedDownloads),
        ("resource download validates bytes hashes publication and cancellation", ResourceDownloadsValidateActualBytesHashAndNeverOverwrite),
        ("resource catalog filters and validates provider results", ResourceCatalogFiltersAndValidatesProviderResults),
        ("resource icons are bounded cached and restricted to provider", ResourceIconsAreBoundedCachedAndRestrictedToProvider),
        ("resource icon cache honors bytes recency and cancellation", ResourceIconCacheHonorsBytesRecencyAndCancellation),
        ("resource icon disposal rejects late and queued work", ResourceIconDisposalRejectsLateAndQueuedWork),
        ("resource catalog bounds actual response and honors cancellation", ResourceCatalogBoundsActualResponseAndHonorsCancellation),
        ("nested Quilt and JarJar inventory preserves content identity", NestedQuiltAndJarJarInventoryPreservesContentIdentity),
        ("installed loader compatibility requires explicit evidence", InstalledLoaderCompatibilityRequiresExplicitEvidence),
        ("recovery restore command honors selection and rejects stale preview", RecoveryRestoreCommandHonorsSelectionAndRejectsStalePreview),
        ("recovery captures publish complete manifests only", RecoveryCaptureCommitsOnlyCompleteManifests),
        ("persistent addon downloads freeze merged sources and reject invalid identity", PersistentAddonDownloadsFreezeMergedSourcesAndRejectInvalidIdentity),
        ("recovery rejects imported and transplanted authority", RecoveryRejectsImportedAndTransplantedAuthority),
        ("persistent install metadata freezes documents and rejects corruption", PersistentInstallMetadataFreezesDocumentsAndRejectsCorruption),
        ("persistent install metadata serializes publication and honors cancellation", PersistentInstallMetadataSerializesPublicationAndHonorsCancellation),
        ("install task terminal states do not resurrect", InstallTaskTerminalStatesDoNotResurrect),
        ("install task journal preserves choices and rejects invalid records", InstallTaskJournalPreservesChoicesAndRejectsInvalidRecords),
        ("downloads without identity restart every source", DownloadsWithoutIdentityRestartEverySource),
        ("new installation recovers after killed downloader without repeating verified files", NewInstallationRecoversAfterKilledDownloaderWithoutRepeatingVerifiedFile),
        ("install recovery discovery isolates invalid tasks and honors disposition", InstallRecoveryDiscoveryIsolatesInvalidTasksAndHonorsDisposition),
        ("completed install recovery does not repopulate task center", CompletedInstallRecoveryDoesNotRepopulateTaskCenter),
        ("install recovery repairs committed terminal before rejecting rollback", InstallRecoveryRepairsCommittedTerminalBeforeRejectingRollback),
        ("install recovery continues preparation and rejects concurrent execution", InstallRecoveryContinuesPreparationAndRejectsConcurrentExecution),
        ("install publication survives process termination", InstallPublicationSurvivesProcessTermination),
        ("install publication preserves external changes and rejects tampering", InstallPublicationPreservesChangedFilesAndRejectsTampering),
        ("recovery coordinator commits and compensates settings", RecoveryCoordinatorCommitsAndCompensatesSettings),
        ("recovery coordinator reopens interrupted settings commit", RecoveryCoordinatorReopensInterruptedSettingsCommit),
        ("recovery file transaction restores selected files and reverses", RecoveryFileTransactionRestoresOnlySelectedFilesAndReverses),
        ("recovery file transaction compensates partial failure and preserves conflicts", RecoveryFileTransactionRevertsPartialFailureAndPreservesConflicts),
        ("recovery file transaction rejects stale and out of scope edits", RecoveryFileTransactionRejectsStaleAndOutOfScopeEdits),
        ("recovery history retains references and defaults to latest only", RecoveryHistoryRetainsReferencesAndDefaultsToLatestOnly),
        ("recovery history preserves previous isolation scope", RecoveryHistoryPreservesPreviousIsolationScope),
        ("recovery preparation verifies complete deduplicated staging", RecoveryPreparationVerifiesAllObjectsWithoutChangingLiveFiles),
        ("recovery preparation rejects corrupt stale and cancelled inputs", RecoveryPreparationRejectsCorruptAndStaleSnapshots),
        ("recovery diff reports files and settings without changing baseline", RecoveryDiffReportsFilesAndPrivateSettingsWithoutChangingBaseline),
        ("recovery diff respects shared scope and unrelated versions", RecoveryDiffHandlesSharedScopeAndNeverClaimsOtherVersionFiles),
        ("exclusive recovery excludes operations and allows existing nested work", RecoveryRestoreExcludesOperationsWithoutDeadlockingNestedWork),
        ("exclusive recovery cancellation releases waiters", RecoveryRestoreCancellationReleasesWaitersAndYieldsCapture),
        ("install waits for exclusive recovery before writing", InstallWaitsForExclusiveRecoveryBeforeWriting),
        ("recovery captures yield without serializing operations", RecoveryCaptureYieldsToOperationsWithoutSerializingThem),
        ("recovery cancellation releases pending reservations", RecoveryGateCancellationDoesNotLeakReservations),
        ("install cancels snapshot before writing files", InstallCancelsSnapshotBeforeWritingFiles),
        ("recovery service captures only complete successful exits", RecoveryServiceCapturesOnlyConfirmedCompleteSuccessfulExits),
        ("Jvm host successful exit automatically captures recovery baseline", JvmHostSuccessfulExitAutomaticallyCreatesRecoveryBaseline),
        ("instance rename preserves data settings and dependencies", InstanceRenamePreservesDataSettingsAndDependencies),
        ("instance rename rejects active games and rolls back settings failure", InstanceRenameRejectsActiveGamesAndRollsBackSettingsFailure),
        ("rename journal resumes every interrupted prefix and rolls back", RenameJournalResumesEveryInterruptedPrefixAndRollsBack),
        ("rename only pending install resumes without reinstalling", RenameOnlyPendingInstallResumesWithoutReinstalling),
        ("component publication and rename recover as one task", ComponentPublicationAndRenameRecoverAsOneTask),
        ("recovery plans include dependencies and protect worlds", RecoveryPlanIncludesDependenciesAndProtectsUserWorlds),
        ("recovery plans use shared game scope and bounded manifests", RecoveryPlanUsesSharedGameDirectoryAndBoundsManifestReads),
        ("recovery objects deduplicate and verify actual bytes", RecoveryObjectsDeduplicateAndVerifyActualBytes),
        ("recovery baselines require a confirmed successful session", Sync(RecoveryBaselineRequiresConfirmedSuccess)),
        ("mod toggles guard files and running directory identities", ModTogglePreservesFilesAndGuardsIdentity),
        ("instance content enumeration is bounded and cancellable", Sync(InstanceContentIsBoundedAndCancellable)),
        ("recovery recognizes launcher mod toggles and restores both paths", RecoveryRecognizesLauncherModTogglesAndRestoresBothPaths),
        ("loader installs are independent unless opted into inheritance", LoaderInstallsAreIndependentUnlessOptedIn),
        ("instance management follows enabled capabilities", Sync(InstanceManagementPagesFollowEnabledCapabilities)),
        ("instance management reads exact instance", InstanceManagementReadsExactInstance),
        ("content metadata uses local names and bounded media", ContentMetadataUsesLocalNamesAndBoundedMedia),
        ("content graph distinguishes metadata evidence and aliases", Sync(ContentGraphDistinguishesEvidenceAndAliases)),
        ("content graph finds actual cycles without marking tails", Sync(ContentGraphFindsActualCyclesWithoutMarkingTails)),
        ("content graph budgets never turn truncation into missing", Sync(ContentGraphBudgetsNeverConvertTruncationIntoMissing)),
        ("content graph isolates selected instances and optional projection", ContentGraphUsesOnlyTheSelectedInstanceAndRequestedProjection),
        ("mod categories distinguish problems unknown and verified updates", ModCategoriesDistinguishProblemsUnknownAndVerifiedUpdates),
        ("mod update checks reject file mutation and retire stale conclusions", ModUpdateCheckRejectsChangedContentAndClearsOldConclusions),
        ("telemetry transport reports bounded failures", TelemetryTransportReportsBoundedFailures),
        ("local OptiFine uses static field constants", LocalOptiFineUsesFieldConstants),
        ("resource history requires matching persisted settings", Sync(ResourceHistoryRequiresMatchingPersistedSettings)),
        ("resource history requires matching mod identities", Sync(ResourceHistoryRequiresMatchingModIdentity)),
        ("host history rejects unsuitable runs and preserves peak semantics", Sync(HostHistoryAdmissionPreservesPeakSemantics)),
        ("empty online model retires cached parameters", EmptyOnlineModelRetiresCachedParameters),
        ("resource history isolated by full instance directory", Sync(ResourceHistoryIsolatedByInstanceDirectory)),
        ("settings queries do not wait for durable writes", SettingsQueriesDoNotWaitForDurableWrites),
        ("resource estimate excludes disabled mods", Sync(ResourceEstimateExcludesDisabledMods)),
        ("resource estimates remain advisory and count heap once", Sync(ResourceEstimatesRemainAdvisoryAndCountHeapOnce)),
        ("nested Fabric inventory reads declared candidates", NestedFabricInventoryReadsDeclaredCandidates),
        ("nested Fabric inventory rejects incomplete and deep archives", NestedFabricInventoryRejectsIncompleteAndDeepArchives),
        ("online resource model admission and prediction stay bounded", Sync(OnlineModelAdmissionAndPredictionStayBounded)),
        ("online resource download keeps only admitted unexpired data", OnlineModelDownloadKeepsOnlyAdmittedUnexpiredData),
        ("schema-1 classpath model cannot override local resource estimates", Sync(OnlineProjectionPreservesResourceSemantics)),
        ("online model session cancels pending refresh", OnlineModelSessionCancelsPendingRefresh),
        ("protected profiles migrate without plaintext copies", ProtectedProfilesMigrateWithoutPlaintextCopies),
        ("protected profile failures preserve original", ProtectedProfileFailuresPreserveOriginal),
        ("native profile protection uses current user", NativeProfileProtectionUsesCurrentUser),
        ("Microsoft refresh cannot restore removed accounts", MicrosoftRefreshCannotRestoreRemovedAccounts),
        ("LittleSkin refresh rejects stale generations at every stage", LittleSkinRefreshRejectsStaleGenerations),
        ("first run persists storage and consent without overwriting", FirstRunPersistsChoiceAndPreservesExistingData),
        ("first run failed commit rolls back and can retry", FirstRunFailedCommitCanRetryWithoutOverwriting),
        ("instance settings reach the launch request", Sync(InstanceSettingsReachTheLaunchRequest)),
        ("Windows digitizer flags distinguish touch and pen", Sync(WindowsDigitizerFlagsDistinguishTouchAndPen)),
        ("machine registry seals typed dependency graph", Sync(MachineRegistrySealsTypedDependencyGraph)),
        ("machine broker coalesces isolates and caches", MachineBrokerCoalescesIsolatesAndCaches),
        ("machine memory and preflight keep independent semantics", Sync(MachineMemoryAndPreflightKeepIndependentSemantics)),
        ("environment projections answer for the primary instance", EnvironmentProjectionsAnswerForThePrimaryInstance),
        ("account projection reads the roster", AccountProjectionReadsTheRoster),
        ("derivation pass computes cross-provider facts", DerivationPassComputesCrossProviderFacts),
        ("form factor heuristic classifies the device", FormFactorHeuristicClassifiesTheDevice),
        ("Linux input uses capability bits and preserves unknown", () => { LinuxInputUsesCapabilityBitsAndPreservesUnknown(); return ValueTask.CompletedTask; }),
        ("native input probe enumerates without hooks", NativeInputProbeEnumeratesWithoutHooks),
        ("content removal is recoverable and rejects conflicts", ContentRemovalIsRecoverableAndRejectsConflicts),
        ("input usage is session local and explicit", Sync(InputUsageIsSessionLocalAndExplicit)),
        ("estimator preflight and remediation remain layered", Sync(EstimatorPreflightAndRemediationRemainLayered)),
        ("remediation actions require exact handlers", RemediationActionsRequireExactHandlers),
        ("JVM host describes the process boundary", Sync(JvmHostDescribesTheProcessBoundary)),
        ("JVM host transport owns bootstrap and cancellation", JvmHostTransportOwnsBootstrapAndCancellation),
        ("Minecraft launch requires private argument transport", MinecraftLaunchRequiresPrivateArgumentTransport),
        ("JVM bootstrap preserves explicit boundaries and rejects malformed frames", JvmBootstrapPreservesBoundaryAndRejectsMalformedFrames),
        ("settings catalog locks final IA and developer visibility", Sync(SettingsCatalogLocksFinalIa)),
        ("settings policy uses sealed foundation routes", SettingsPolicyUsesSealedFoundationRoutes),
        ("settings legacy strategies preserve units and choices", Sync(SettingsLegacyStrategiesKeepTheirMeaning)),
        ("settings argument rows preserve quoted values", Sync(SettingsArgumentRowsPreserveQuotedValues)),
        ("settings Java preference reaches launch selection", Sync(SettingsJavaPreferenceReachesLaunchSelection)),
        ("migrated Java and memory settings survive restart and reject invalid values", Sync(MigratedJavaAndMemorySettingsSurviveRestartAndRejectInvalidValues)),
        ("recovery setting plans restore selected overrides and compensate", Sync(RecoverySettingPlansRestoreOnlySelectedOverridesAndCompensate)),
        ("recovery setting plans reject stale conflicting and wrong scope state", Sync(RecoverySettingPlansRejectStaleAndConflictingState)),
        ("recovery settings preserve private arguments and inheritance", Sync(RecoverySettingsPreservePrivateArgumentsAndInheritance)),
        ("recovery settings reject wrong scope and incomplete baseline", Sync(RecoverySettingsRejectWrongScopeAndIncompleteBaseline)),
        ("settings inheritance distinguishes Auto and isolates instances", Sync(SettingsInheritanceIsExplicitAndIsolated)),
        ("settings overlays resolve in order without enabling mutation", Sync(SettingsOverlayPrecedenceIsPreviewOnly)),
        ("settings batch failures publish nothing and cross validate", Sync(SettingsBatchFailurePublishesNothing)),
        ("settings import is previewed atomic and private", Sync(SettingsImportIsPreviewedAtomicAndPrivate)),
        ("settings reset is scoped previewed and preserves reserved values", Sync(SettingsResetIsScopedPreviewedAndPreservesReservedValues)),
        ("game priority captures scoped preference and legacy meaning", Sync(GamePriorityCapturesScopedPreferenceAndLegacyMeaning)),
        ("game window preferences capture scopes and legacy values", Sync(GameWindowPreferencesCaptureScopesAndLegacyValues)),
        ("default isolation preserves legacy scope and unknown facts", Sync(DefaultIsolationPolicyPreservesLegacyScopeAndUnknownFacts)),
        ("default isolation controls addons and protects orphan metadata", DefaultIsolationControlsAddonDestinationAndRejectsOrphanMetadata),
        ("game window preferences reach tracked process", GameWindowPreferencesReachTrackedProcess),
        ("game priority control failure cannot fail started session", GamePriorityControlFailureCannotFailStartedSession),
        ("Java inventory runs on worker and refreshes without state writes", JavaInventoryRunsOnWorkerAndRefreshesWithoutStateWrites),
        ("Java inventory rejects late noncooperative discovery", JavaInventoryRejectsLateNoncooperativeDiscovery),
        ("settings reset rejects stale revision and rolls back save failure", Sync(SettingsResetRejectsStaleRevisionAndRollsBackSaveFailure)),
        ("settings layers survive restart and preserve unknown data", Sync(SettingsLayersSurviveRestartAndPreserveUnknowns)),
        ("Java major choices select installed runtimes or acquire missing ones", JavaMajorChoiceUsesInstalledOrDownloads),
        ("process output drains and abnormal exit is analyzed", ProcessOutputDrainsAndAbnormalExitIsAnalyzed),
        ("folder import preserves source and rejects conflicts", FolderImportPreservesSourceAndRejectsConflicts),
        ("folder import rejects malformed manifests", FolderImportRejectsMalformedManifests),
        ("local jar imports preserve instance and core", LocalJarImportsPreserveInstanceAndCore),
        ("local jar rejects stored length mismatch", LocalJarRejectsStoredLengthMismatch),
        ("legacy metadata without core patch can be checked", LegacyMetadataWithoutCorePatchCanBeChecked),
        ("local jar installer uses content identity", LocalJarInstallerUsesContentIdentity),
        ("local installer does not download replacement", LocalInstallerDoesNotDownloadReplacement),
        ("mrpack installs client files and overrides atomically", MrpackInstallsClientFilesAndOverridesAtomically),
        ("modpack failures never publish instance", ModpackFailuresNeverPublishInstance),
        ("archive actual byte limits and stored length mismatch", ArchiveActualByteLimits),
        ("modpack cancellation and conflicts preserve existing data", ModpackCancellationAndConflictsPreserveExistingData),
        ("modpack recovery uses pinned archive and verified downloads", ModpackRecoveryUsesPinnedArchiveAndReusesVerifiedDownloads),
        ("modpack publication recovers lost completion and protects changed files", ModpackPublicationRecoversLostCompletionAndProtectsChangedFiles),
        ("cancel queued modpack prevents startup recovery", CancelQueuedModpackPreventsStartupRecovery),
        ("CurseForge packs honor file identity and download restrictions", CursePackResolvesFilesAndHonorsDownloadRestrictions),
        ("library deletion is contained and recoverable", LibraryDeleteIsContainedAndRecoverable),
        ("launch completion repairs missing files before start", LaunchCompletionRepairsMissingFilesBeforeStart),
        ("install preserves game identity and selected addon artifact", InstallKeepsGameIdentityAndSelectedAddonArtifact),
        ("install runs the real pipeline into the version library", InstallRunsTheRealPipelineIntoTheVersionLibrary),
        ("install rejects processor loaders before touching disk", InstallRejectsProcessorLoadersBeforeTouchingDisk),
        ("install cancel marks the task canceled", InstallCancelMarksTheTaskCanceled),
        ("install exit rejects corrupt queue and allows rollback retry", InstallExitRejectsCorruptQueueAndAllowsRollbackRetry),
        ("install exit applies to queued roots before they start", InstallExitAppliesToQueuedRootsBeforeTheyStart),
        ("install exit pause retains plan and cancel removes stage", InstallExitPauseRetainsPlanAndCancelRemovesStage),
        ("loader installer cache pins identity and rejects changes", LoaderInstallerCachePinsIdentityAndRejectsChanges),
        ("owned installer dies after owner is killed", OwnedInstallerDiesAfterOwnerIsKilled),
        ("task center tracks lifecycle and summary", TaskCenterTracksLifecycleAndSummary),
        ("task center pause preserves checkpoint without completing steps", TaskCenterPausePreservesCheckpointWithoutCompletingSteps),
        ("prerelease telemetry cannot be disabled", PrereleaseTelemetryCannotBeDisabled),
        ("telemetry lifecycle records only bounded facts", TelemetryLifecycleRecordsOnlyBoundedFacts),
        ("diagnostic revocation preserves necessary facts", DiagnosticRevocationPreservesNecessaryFacts),
        ("diagnostic metrics and errors respect consent and schema", DiagnosticMetricsAndErrorsRespectConsentAndSchema),
        ("whole run sampling retains history and private settings", () => { RunSamplingRetainsWholeRunAndPrivateSettings(); return ValueTask.CompletedTask; }),
        ("mod inventory uses metadata and marks partial evidence", () => { ModInventoryUsesMetadataAndMarksPartialEvidence(); return ValueTask.CompletedTask; }),
        ("preflight gate rejects stale and blocked continuation", PreflightGateRejectsStaleAndBlockedContinuation),
        ("preflight scope carries policy and cancels providers", PreflightScopeCarriesPolicyAndCancelsProviders),
        ("preflight refresh reads changed instance", PreflightRefreshReadsChangedInstance),
        ("rollouts keep cohorts and fail closed", RolloutsKeepCohortsAndFailClosed),
        ("Nexa updates reject legacy and wrong platform", NexaUpdatesRejectLegacyAndWrongPlatform),
        ("folder import requires resolvable parents", FolderImportRequiresResolvableParents),
        ("folder import copies only required parent artifacts", FolderImportCopiesOnlyRequiredParentArtifacts),
        ("task center serializes terminal reuse and dismiss races", TaskCenterSerializesRaces),
        ("task center cancel routes to owner token", TaskCenterCancelRoutesToOwnerToken),
        ("task center rejects cancel of protected tasks", TaskCenterRejectsCancelOfProtectedTasks),
        ("task center bounds terminal history for every terminal kind", TaskCenterBoundsTerminalHistoryForEveryTerminalKind),
        ("task center stages never move backwards", TaskCenterStagesNeverMoveBackwards),
        ("task center abandoned handles surface as failed", TaskCenterAbandonedHandlesSurfaceAsFailed),
        ("task center clear finished leaves active", TaskCenterClearFinishedLeavesActive),
        ("install catalog addon sources merge and isolate failures", InstallAddonSourcesMergeAndIsolateFailures),
        ("install catalog prefetch retains sibling results and cancellation", InstallPrefetchRetainsSiblingResultsAndCancellation),
        ("install catalog eligibility owns transitions and projection", InstallEligibilityOwnsTransitionsAndProjection),
        ("install catalog validates OptiFine and OptiFabric published dependencies", InstallBuildCompatibilityUsesPublishedMetadata),
        ("install catalog parses all provider formats and compatibility boundaries", InstallCatalogParsesProviderContracts),
        ("install catalog rejects stale responses and distinguishes unsupported", InstallCatalogRejectsStaleResults),
        ("installed version families preserve legacy icon distinctions and inheritance", InstalledVersionKindsPreserveLegacyDistinctions),
        ("library selections retain directory identity and survive restart", LibraryRemembersDirectoryQualifiedSelection),
        ("library rejects stale scans and preserves newer selections", LibraryRejectsStaleScansAndPreservesLiveSelection),
        ("library save failures and unavailable roots preserve truth", LibraryFailedSavesAndUnavailableRootsRemainHonest),
        ("library preserves unknown persisted schemas", LibraryUnknownDocumentsArePreserved),
        ("operation breadcrumbs retain stage source and one terminal outcome", Sync(OperationBreadcrumbsKeepStageSourceAndOneOutcome)),
        ("diagnostic redaction covers quoted secrets and device codes", Sync(DiagnosticRedactionCoversQuotedSecretsAndDeviceCodes)),
        ("foundation startup failures reach configured sinks", Sync(FoundationStartupFailuresReachConfiguredSinks)),
        ("settings diagnostics hide values and explain durable failure", Sync(SettingsDiagnosticsHideValuesAndExplainDurableFailure)),
        ("production routes and login workers emit diagnostics", ProductionRoutesAndLoginWorkersEmitDiagnostics),
        ("download commit failures identify the failed stage", DownloadCommitFailureLogsItsStage),
        ("native preparation failures log before process start", NativePreparationFailureLogsBeforeProcessStart),
        ("HTTP diagnostics exclude secrets and preserve responses", HttpDiagnosticsExcludeSecretsAndPreserveResponses),
        ("dispatch start observers cannot break handlers", DispatchStartObserversCannotBreakHandlers),
        ("profile skins resolve explicit and session textures without credentials", ProfileSkinsResolveExplicitAndSessionTextures),
        ("removed profiles reject late skin responses", RemovedProfilesRejectLateSkinResponses),
        ("profile imports validate deduplicate and persist before publication", Sync(ProfileImportIsValidatedDeduplicatedAndDurable)),
        ("legacy import never repairs or writes source data", LegacyImportNeverRepairsOrWritesSource),
        ("account authorization addresses stay on provider origins", Sync(AccountAuthorizationUrlsStayOnProviderOrigins)),
        // XSR-501: settings capability contract.
        ("schema defaults are visible and available", Sync(SchemaDefaultsAreVisibleAndAvailable)),
        ("set then get round trips every type", SetThenGetRoundTripsEveryType),
        ("raw values round trip every declared type", RawValuesRoundTripEveryDeclaredType),
        ("unknown keys are rejected stably", UnknownKeyIsRejectedStably),
        ("type mismatches are rejected stably", TypeMismatchIsRejectedStably),
        ("null values are rejected and text is port-agnostic", NullValuesAreRejectedAndTextIsPortAgnostic),
        ("set persists and survives restart", SetPersistsAndSurvivesRestart),
        ("corrupt and unknown persisted entries are skipped", CorruptAndUnknownPersistedEntriesAreSkipped),
        ("failed save returns a stable error and mutates nothing", FailedSaveReturnsStableErrorAndMutatesNothing),
        ("failed load keeps defaults but marks unavailable", FailedLoadKeepsDefaultsButMarksUnavailable),
        ("reset value and reset all restore defaults", ResetValueAndResetAllRestoreDefaults),
        ("reset all with a failed save mutates nothing", ResetAllFailedSaveMutatesNothing),
        ("the state observer sees every applied change", StateObserverSeesEveryAppliedChange),
        ("the file port round trips and skips malformed lines", FilePortRoundTripsAndSkipsMalformedLines),
        ("the file port writes sorted ordinal entries", FilePortWritesSortedOrdinalEntries),
        ("the line port rejects unrepresentable values", LinePortRejectsUnrepresentableValues),
        // XSR-503: launcher settings file compatibility.
        ("the launcher schema matches the legacy defaults", LauncherSchemaMatchesLegacyDefaults),
        ("the json port round trips the legacy shape", JsonPortRoundTripsLegacyShape),
        ("the json port writes legacy fixed field defaults on fresh save", JsonPortWritesFreshFixedFieldDefaults),
        ("the json port quarantines an unsupported schema", JsonPortQuarantinesUnsupportedSchema),
        ("the json port recovers invalid items and quarantines", JsonPortRecoversInvalidItems),
        ("the json port treats a missing file as empty", JsonPortMissingFileIsEmpty),
        ("the json port preserves unknown fields and keys", JsonPortPreservesUnknownContent),
        ("settings over the json port persist end to end", SettingsOverJsonPortEndToEnd),
        // XSR-504: download capability contract.
        ("downloads fail over across sources", DownloadFailsOverAcrossSources),
        ("downloads fail when every source fails", DownloadFailsWhenEverySourceFails),
        ("writer temp files survive for resume", WriterTempFileSurvivesForResume),
        ("concurrent downloaders share one transfer", ConcurrentDownloadersShareOneTransfer),
        ("progress stages flow in order", ProgressStagesFlowInOrder),
        ("throwing progress handlers keep the transfer alive", ThrowingProgressHandlerKeepsTransferAlive),
        ("cancellation rejects the transfer", CancellationRejectsTheTransfer),
        ("segmented downloads assemble parallel parts", SegmentedDownloadAssemblesParallelParts),
        ("segmented falls back to single stream when unsupported", SegmentedFallsBackToSingleStreamWhenUnsupported),
        ("segmented falls back for files below the segment floor", SegmentedFallsBackForFilesBelowTheSegmentFloor),
        ("segmented range mismatches fail over to the next source", SegmentedRangeMismatchFailsOverToNextSource),
        ("segmented truncated sources fail over to the next source", SegmentedTruncatedSourceFailsOverToNextSource),
        ("segmented progress reaches completed at full length", SegmentedProgressReachesCompletedAtFullLength),
        // XSR-506: account capability contract.
        ("launch profiles round trip the legacy json shape", ProfilePortRoundTripsLegacyJsonShape),
        ("the profile port quarantines unreadable files", ProfilePortQuarantinesUnreadableFiles),
        ("profiles persist across restarts", ProfilesPersistAcrossRestarts),
        ("invalid profiles and indexes are rejected stably", InvalidProfilesAndIndexesAreRejectedStably),
        ("failed saves change nothing observable", FailedSavesChangeNothingObservable),
        ("provider id equality is case insensitive", Sync(ProviderIdEqualityIsCaseInsensitive)),
        // XSR-507: update block data contracts.
        ("chunk profiles match the legacy bounds", ChunkProfilesMatchLegacyBounds),
        ("chunking is deterministic and covers the file", ChunkerIsDeterministicAndCoversTheFile),
        ("block codec normalizes and detects codecs", BlockCodecNormalizesAndDetectsCodecs),
        ("block codec round trips and verifies both codecs", BlockCodecRoundTripsAndVerifiesBothCodecs),
        ("block codec detects mismatched declarations", BlockCodecDetectsMismatchedDeclaration),
        ("the local block index round trips the installed map", LocalBlockIndexRoundTripsTheInstalledMap),
        ("the local block index verifies before reusing chunks", LocalBlockIndexVerifiesBeforeReusingChunks),
        ("the local block index reads verified windows", LocalBlockIndexReadsVerifiedWindows),
        // One-way upgrade policy.
        ("the legacy one-four line crosses into two point zero", Sync(LegacyOneFourCrossesIntoTwoPointZero)),
        ("alpha beta stable ordering is monotonic", Sync(AlphaBetaStableOrderingIsMonotonic)),
        ("the same version is a no-op", Sync(SameVersionIsANoOp)),
        ("ci builds hop by commit", Sync(CiBuildsHopByCommit)),
        ("unrecognized versions are refused", Sync(UnrecognizedVersionsAreRefused)),
        ("version parsing normalizes legacy shapes", Sync(VersionParsingNormalizesLegacyShapes)),
        ("build identity preserves policy channels", Sync(BuildIdentityPreservesPolicyChannels)),
        // XSR-509: update package planning.
        ("the patch index deserializes the legacy json", Sync(PatchIndexDeserializesLegacyJson)),
        ("build identity normalizes variants and configurations", Sync(BuildIdentityNormalizesVariantsAndConfigurations)),
        ("full package composition matches layout and channel", Sync(FullPackageCompositionMatchesLayoutAndChannel)),
        ("direct patch paths fall back to release asset urls", Sync(DirectPatchPathIsPlannedWithAssetUrlFallback)),
        ("cheaper patch kinds win and unworthwhile chains fall back", Sync(CheaperPatchKindWinsAndUnworthwhileChainsFallBackToFull)),
        ("unusable indexes return null for full fallback", Sync(UnusableIndexesReturnNullForFullFallback)),
        ("variant matching normalizes runtime variants", Sync(VariantMatchingNormalizesRuntimeVariants)),
        ("multi-hop paths are planned across indexes", Sync(MultiHopPathIsPlannedAcrossIndexes)),
        ("block map windows and baseline gate the shortcuts", Sync(BlockMapWindowsAndBaselineGateTheShortcuts)),
        // XSR-510: update discovery and transport.
        ("index fetch follows preference and fallback rules", IndexFetchFollowsPreferenceAndFallbackRules),
        ("the github fallback url is tried only when enabled", GithubFallbackUrlIsTriedOnlyWhenEnabled),
        ("eligibility gates before any network", EligibilityGatesBeforeAnyNetwork),
        ("baseline and single file skip index fetch", BaselineAndSingleFileSkipIndexFetch),
        ("the multi-tag walk loads previous indexes until a path is found", MultiTagWalkLoadsPreviousIndexesUntilPathFound),
        ("the walk stops when the previous target is not newer", WalkStopsWhenPreviousTargetIsNotNewer),
        ("head failures fall back to the index archive size", HeadFailureFallsBackToIndexArchiveSize),
        // XSR-511: signature and delta codecs.
        ("vcdiff decodes add copy and run instructions", Sync(VcdiffDecodesAddCopyAndRunInstructions)),
        ("vcdiff rejects unsupported and corrupt deltas", Sync(VcdiffRejectsUnsupportedAndCorruptDeltas)),
        ("gpg verifier accepts a genuine detached signature", GpgVerifierAcceptsGenuineDetachedSignature),
        ("gpg policy rejects weak hashes and text signatures", GpgPolicyRejectsWeakHashesAndTextSignatures),
        ("gpg policy uses trusted key and authenticated expiry", GpgPolicyUsesTrustedKeyAndAuthenticatedExpiry),
        ("gpg policy bounds envelopes and keeps cancellation", GpgPolicyBoundsEnvelopesAndKeepsCancellation),
        ("gpg verifier rejects tampered foreign and unpinned keys", GpgVerifierRejectsTamperedForeignAndUnpinnedKeys),
        // XSR-512: staged install core.
        ("staged tree verification rejects mismatches", Sync(StagedTreeVerificationRejectsMismatches)),
        ("flattening collapses single package wrapper roots", Sync(FlattenSingleRootCollapsesWrapperFolders)),
        ("update discovery binds every version", UpdateDiscoveryBindsEveryVersion),
        ("update deletion requires signed ownership", UpdateDeletionRequiresSignedOwnership),
        ("plan building preserves unknown files", Sync(BuildPlanInventoriesManagedLeftovers)),
        ("applying a plan refuses unprotected mutation", Sync(ApplyPlanRefusesUnprotectedMutation)),
        ("unsafe paths are refused everywhere", Sync(UnsafePathsAreRefusedEverywhere)),
        ("protected update high-water is monotonic and durable", Async(UpdateHighWaterStoreIsMonotonicAndDurable)),
        // XSR-706: product launch orchestration inputs.
        ("offline identity falls back to the vanilla uuid", Sync(OfflineIdentityFallsBackToVanillaUuid)),
        ("offline uuids match vanilla golden values", Sync(OfflineUuidsMatchVanillaGoldenValues)),
        ("offline profile uuid migration repairs the legacy roster", Sync(OfflineProfileUuidMigrationRepairsLegacyRoster)),
        ("launch coordinator builds a complete low level request", Async(LaunchCoordinatorBuildsCompleteLowLevelRequest)),
        ("launch coordinator rejects incomplete inheritance", Async(LaunchCoordinatorRejectsIncompleteInheritance)),
        ("production minecraft runtime registers product start", Sync(ProductionMinecraftRuntimeRegistersStartRoute)),
        // XSR-519: Wave 5 acceptance integration.
        ("foundation composition end to end", FoundationCompositionEndToEnd),
        ("foundation downloads use composed logging", FoundationDownloadsUseComposedLogging),
        ("file sink appends and survives io errors", FileSinkAppendsAndSurvivesIoErrors),
        ("console sink disables instead of throwing", Sync(ConsoleSinkDisablesInsteadOfThrowing)),
        ("level gate policy holds across tiers", Sync(LevelGatePolicyHoldsAcrossTiers)),
        // XSR-712: launch progress narration.
        ("launch stage weights match the legacy table", Sync(LaunchStageWeightsMatchLegacyTable)),
        ("progress publisher writes coherent cells", Sync(ProgressPublisherWritesCoherentCells)),
        ("cancel active launch without launch returns false", Sync(CancelActiveLaunchWithoutLaunchReturnsFalse)),
        ("launch pipeline narrates stages and reaches launched", LaunchPipelineNarratesStagesAndReachesLaunchedAsync),
        ("java acquisition waits for a decision and denial fails the launch", JavaAcquisitionWaitsForDecisionAndDenialFailsLaunch),
        ("java acquisition approval downloads and launches", JavaAcquisitionApprovalDownloadsAndLaunches),
        ("Java auto-install uses settings and preserves explicit runtime errors", JavaAutoInstallUsesSettingsWithoutApprovalAndPreservesExplicitRuntime),
        ("a second concurrent launch is rejected as already active", SecondConcurrentLaunchIsRejectedAsAlreadyActive),
        ("unsupported account kinds refuse to launch", UnsupportedAccountKindsRefuseToLaunch),
        ("immediate exit after process start resets launch progress", ImmediateExitAfterProcessStartResetsLaunchProgress),
        ("cancel racing with launch completion never throws", CancelRacingWithLaunchCompletionNeverThrows),
        ("x11 window probe finds a real window", X11WindowProbeFindsARealWindow),
        ("cancelling during the window wait terminates the process", CancelDuringWindowWaitTerminatesTheProcess),
        ("an unsupported probe skips the wait without burning the limit", UnsupportedProbeSkipsTheWaitWithoutBurningTheLimit),
        ("onboarding composition arms refresh capability without explicit microsoft", Sync(OnboardingCompositionArmsRefreshCapabilityWithoutExplicitMicrosoft)),
        ("offline legacy uuid launches correctly when the migration save fails", Sync(OfflineLegacyUuidLaunchesCorrectlyWhenMigrationSaveFails)),
        ("java probe parses modern property output", Sync(JavaProbeParsesModernPropertyOutput)),
        ("java probe parses the legacy version line", Sync(JavaProbeParsesLegacyVersionLine)),
        ("java probe rejects unrecognized output", Sync(JavaProbeRejectsUnrecognizedOutput)),
        ("java expand root finds homes in vendor trees", Sync(ExpandRootFindsHomesInVendorTrees)),
        ("java search retains a direct-path shim executable", Sync(JavaSearchRetainsDirectPathShimExecutable)),
        ("cross capability page has no state id collisions", CrossCapabilityPageHasNoStateIdCollisions),
        // XSR-513: online account flows.
        ("the microsoft device login runs the full chain", MicrosoftDeviceLoginRunsTheFullChain),
        ("microsoft declined and expired are distinct errors", MicrosoftDeclinedAndExpiredAreDistinctErrors),
        ("microsoft refresh runs the chain without a device code", MicrosoftRefreshRunsTheChainWithoutDeviceCode),
        ("yggdrasil authenticate validate and refresh run", YggdrasilAuthenticateValidateAndRefreshRun),
        ("yggdrasil failures surface the server message", YggdrasilFailureSurfacesServerMessage),
        ("yggdrasil server normalization and jwt expiry work", Sync(YggdrasilServerNormalizationAndJwtExpiry)),
        ("login results feed the persisted roster", LoginResultsFeedThePersistedRoster),
        // XSR-516: payload extraction and patch orchestration.
        ("update archives enforce actual budgets", UpdateArchivesEnforceActualBudgets),
        ("zip payloads extract with traversal refusal", Sync(ZipPayloadsExtractWithTraversalRefusal)),
        ("tar payloads extract with modes", TarPayloadsExtractWithModes),
        ("the hpatchz tool runs through the process port", HpatchzToolRunsThroughTheProcessPort),
        ("binary patch chains verify download and apply", BinaryPatchChainsVerifyDownloadAndApply),
        ("scatter ops produce a verified staged tree", ScatterOpsProduceAVerifiedStagedTree),
        // XSR-514: LittleSkin OAuth and appearance services.
        ("the littleskin device flow runs to tokens", LittleSkinDeviceFlowRunsToEnd),
        ("littleskin token paths and invalid client behave", LittleSkinTokenPathsAndInvalidClient),
        ("littleskin profiles session closet and apply run", LittleSkinProfilesSessionClosetAndApply),
        ("littleskin texture upload uses the minecraft token", LittleSkinTextureUploadUsesMinecraftToken),
        ("microsoft skin upload parses the active texture", MicrosoftSkinUploadParsesActiveTexture),
        ("microsoft cape service lists and activates", MicrosoftCapeServiceListsAndActivates),
        // XSR-517: Network and Telemetry families.
        ("network probes report reachability and latency", NetworkProbesReportReachabilityAndLatency),
        ("telemetry revocation clears and private fields are rejected", TelemetryRevocationClearsAndTransportRejectsPrivateFields),
        ("telemetry without consent records nothing", Sync(TelemetryWithoutConsentRecordsNothing)),
        ("telemetry buffers with bounded eviction", Sync(TelemetryBuffersWithBoundedEviction)),
        ("telemetry flush uploads and clears or retains", TelemetryFlushUploadsAndClearsOrRetains),
        ("telemetry batch serialization is stable", Sync(TelemetryBatchSerializationIsStable)),
        // XSR-751: caller staging is never protected-helper authority.
        ("protected update scheduling refuses caller controlled executable", Sync(UpdateSchedulingRefusesCallerControlledExecutable)),
        ("protected update scheduling refuses before inspecting missing artifacts", Sync(UpdateSchedulingRefusesBeforeInspectingMissingArtifacts)),
        ("staged path helpers sanitize versions", Sync(StagedPathHelpersSanitizeVersions)),
        // XSR-606: Wave 6 acceptance hardening.
        ("conflicting java ranges are rejected", Sync(ConflictingJavaRangesAreRejected)),
        ("overlapping java ranges narrow correctly", Sync(OverlappingJavaRangesNarrowCorrectly)),
        ("minecraft java gates use normalized coordinates", Sync(MinecraftJavaGatesUseNormalizedCoordinates)),
        ("minecraft Java era matrix matches the release line", Sync(MinecraftJavaEraMatrixMatchesReleaseLine)),
        ("calendar Minecraft versions retain their scheme", Sync(MinecraftCalendarVersionsRetainTheirScheme)),
        ("manifest Java metadata is authoritative", Sync(ManifestJavaMetadataIsAuthoritative)),
        ("minecraft 1.16.5 never selects Java 7", Minecraft1165NeverSelectsJava7),
        ("minecraft 1.20.1 never selects Java 8", Minecraft1201NeverSelectsJava8),
        ("modern jvm tokens all resolve", ModernJvmTokensAllResolve),
        ("unresolved launch token fails planning", UnresolvedLaunchTokenFailsPlanning),
        ("unknown jvm token fails planning", UnknownJvmTokenFailsPlanning),
        ("vanilla launch contains client jar", VanillaLaunchContainsClientJar),
        ("inherited launch uses base client jar when provided", InheritedLaunchUsesBaseClientJarWhenProvided),
        ("inherited launch resolves base client jar automatically", InheritedLaunchResolvesBaseClientJarAutomatically),
        ("library artifact and native classifier both resolve", Sync(MinecraftLibraryArtifactAndNativeClassifierBothResolve)),
        ("system GLFW keeps the ordinary artifact", Sync(SystemGlfwKeepsOrdinaryArtifact)),
        ("system GLFW drops the native classifier", Sync(SystemGlfwDropsNativeClassifier)),
        ("arm64 native is not on classpath", Arm64NativeIsNotOnClasspath),
        ("natives are extracted before launch", NativesAreExtractedBeforeLaunch),
        ("mojang rule order matches manifest semantics", Sync(MojangRuleOrderMatchesManifestSemantics)),
        ("os version uses regex", Sync(OsVersionUsesRegex)),
        ("absent false feature matches", Sync(AbsentFalseFeatureMatches)),
        ("minecraft library rules use shared evaluator", Sync(MinecraftLibraryRulesUseSharedEvaluator)),
        ("minecraft launch route stages natives before process start", MinecraftLaunchRouteStagesNativesBeforeProcessStart),
        ("minecraft download paths reject manifest traversal", Sync(MinecraftDownloadPathsRejectManifestTraversal)),
        ("canonical corpus produces consistent launch snapshots", CanonicalCorpusProducesConsistentLaunchSnapshots),
        ("process session publishes into host store", ProcessSessionPublishesIntoHostStore),
        // XSR-515: File capability.
        ("the folder tree resolves canonical names", Sync(FolderTreeResolvesCanonicalNames)),
        ("traversal is refused on every port operation", Sync(TraversalIsRefusedOnEveryPortOperation)),
        ("text and bytes round trip atomically", TextAndBytesRoundTripAtomically),
        ("size cap and default root resolution behave", SizeCapAndDefaultRootResolutionBehave),
        ("symlink escapes are rejected", Sync(SymlinkEscapeIsRejected)),
        ("transfer state mirrors active downloads", TransferStateMirrorsActiveDownloads),
        ("the file writer rejects short resume offsets", FileDownloadWriterRejectsShortResume),
        ("doubles round trip through full precision", DoubleRoundTripsThroughFullPrecision),
        // XSR-502: logging capability contract.
        ("log level gate defaults to info and falls back stably", Sync(LogLevelGateDefaultsToInfoAndFallsBackStably)),
        ("modules are normalized before storage", Sync(ModulesAreNormalizedBeforeStorage)),
        ("messages and exceptions are redacted before storage", Sync(MessagesAndExceptionsAreRedactedBeforeStorage)),
        ("the ring evicts oldest beyond capacity", Sync(RingEvictsOldestBeyondCapacity)),
        ("the state collection mirrors the snapshot", Sync(StateCollectionMirrorsSnapshot)),
        ("clear empties the ring and state", Sync(ClearEmptiesRingAndState)),
        ("the redactor covers the legacy secret patterns", Sync(RedactorCoversLegacySecretPatterns)),
        ("observers see appends and never break writes", Sync(ObserversSeeAppendsAndNeverBreakWrites)),
        ("timestamps come from the time provider", Sync(TimestampsComeFromTimeProvider)),
        ("display text matches the legacy format", Sync(DisplayTextMatchesLegacyFormat)),
        ("concurrent writes keep sequence and order", Sync(ConcurrentWritesKeepSequenceAndOrder)),
        // XSR-601: Minecraft version and instance discovery.
        ("minecraft version classifier matches canonical aliases", Sync(MinecraftVersionClassifierMatchesCanonicalAliases)),
        ("minecraft version discovery uses stable safe resolution", Sync(MinecraftVersionDiscoveryUsesStableSafeResolution)),
        ("minecraft instance metadata round trips atomically", MinecraftInstanceMetadataRoundTripsAtomically),
        ("minecraft Java selection honors manifest and availability", MinecraftJavaSelectionHonorsManifestAndAvailability),
        ("minecraft assets resolve canonical object paths", Sync(MinecraftAssetsResolveCanonicalObjectPaths)),
        ("minecraft libraries and classpath honor rules", Sync(MinecraftLibrariesAndClasspathHonorRules)),
        ("minecraft ModLoader and launch plan are deterministic", Sync(MinecraftModLoaderAndLaunchPlanAreDeterministic)),
        ("minecraft crash analysis and dependency parsing are structured", Sync(MinecraftCrashAnalysisAndDependencyParsingAreStructured)),
        ("minecraft runtime composition registers routes", MinecraftRuntimeCompositionRegistersRoutes),
        ("minecraft Java runtime package planner validates manifest", MinecraftJavaRuntimePackagePlannerValidatesManifest),
        ("minecraft download planners respect existing files", Sync(MinecraftDownloadPlannersRespectExistingFiles)),
        ("minecraft Java preference parser preserves legacy semantics", Sync(MinecraftJavaPreferenceParserPreservesLegacySemantics)),
        ("minecraft libraries use ARM64 compatibility artifacts", Sync(MinecraftLibrariesUseArm64CompatibilityArtifacts)),
        ("Editing preserves configuration and locks Minecraft", EditingPreservesConfigurationAndLocksMinecraft),
        ("Editing removes only unchanged managed mods", EditingRemovesOnlyUnchangedManagedMods),
        ("Component edits do not reinstall the base", ComponentEditsDoNotReinstallTheBase),
        ("Edit defaults recognize modern Forge and NeoForge arguments", EditDefaultsRecognizeModernForgeAndNeoForgeArguments),
        ("Failed edit keeps the original manifest", FailedEditKeepsOriginalManifest),
        ("Profile loaders commit without duplicating full manifests", ProfileLoadersCommitWithoutDuplicatingFullManifests),
        ("LiteLoader preserves legacy base arguments", Sync(LiteLoaderPreservesLegacyBaseArguments)),
        ("LabyMod includes bootstrap and pinned artifact", Sync(LabyModIncludesBootstrapAndPinnedArtifact)),
        ("Additional installers isolate output and propagate failure", AdditionalInstallersUseStagingAndPropagateFailure),
        ("Forge and NeoForge stage official installers and validate generated artifacts", ForgeInstallStagesAndValidatesOutputs),
        ("Forge and NeoForge commit manifests after installer completion", ForgeAndNeoForgeCommitInstallerManifestLast),
        ("Forge rejects missing processor output without publishing a version", ForgeInstallRejectsMissingProcessorOutput),
        ("Legacy launches receive native paths and preserve overrides", Sync(LegacyLaunchSuppliesNativePathWithoutOverridingExplicitConfiguration)),
        ("minecraft launch plan merges inherited and modern arguments", Sync(MinecraftLaunchPlanMergesInheritedAndModernArguments)),
        ("minecraft download source planner covers official and unlisted mirrors", Sync(MinecraftDownloadSourcePlannerCoversOfficialAndUnlistedMirrors)),
        ("minecraft Java runtime installer verifies and installs", MinecraftJavaRuntimeInstallerVerifiesAndInstalls),
        ("Java runtime recovery reuses pinned plan and verified files", JavaRuntimeRecoveryReusesPinnedPlanAndVerifiedFiles),
        ("Java runtime rejects actual download overrun", JavaRuntimeRejectsActualDownloadOverrun),
        ("Java runtime stop separates pause and cancel", JavaRuntimeStopSeparatesPauseAndCancel),
    ];

    private static async Task<int> Main(string[] args)
    {
        if (args is [Nexa.Services.Minecraft.Process.MinecraftLaunchHookWorker.WorkerArgument])
            return await Nexa.Services.Minecraft.Process.MinecraftLaunchHookWorker.RunWorkerAsync().ConfigureAwait(false);
        if (args is ["--delta-publisher-smoke", var deltaFixture]) return await RunPublisherDeltaFixture(deltaFixture);
        if (args is ["--update-server-smoke"]) { await AutomaticUpdateLoopbackHttpTransaction(); return 0; }
        if (args is ["--serve-update-fixture"]) return await ServeAutomaticUpdateFixture();
        // Existing parity fixtures model the mainland product; international tests select US explicitly.
        if (Environment.GetEnvironmentVariable("NEXA_COUNTRY") is null) Environment.SetEnvironmentVariable("NEXA_COUNTRY", "CN");
        if (args is ["--owned-installer-child"]) return await RunOwnedInstallerChild();
        if (args is ["--owned-installer-owner"]) return await RunOwnedInstallerOwner();
        if (args is [Nexa.Services.Processes.OwnedInstallerProcess.WorkerArgument]) return await Nexa.Services.Processes.OwnedInstallerProcess.RunWorkerAsync();
        if (args is ["--interrupted-new-install", var installRoot]) return await RunInterruptedNewInstallChild(installRoot);
        if (args is ["--install-publication-child", var root, var stage]) return await RunInstallPublicationChild(root, stage);
        if (args is ["--jvm-host"]) return await ReceiveJvmHostFixture();
        if (args.Contains("--live-install-catalog")) { await LiveInstallCatalogSmoke(); return 0; }
        int passed = 0;
        foreach ((string name, Func<ValueTask> body) in TestCases)
        {
            if (args is { Length: > 0 } && !args.Any(arg => name.Contains(arg, StringComparison.OrdinalIgnoreCase)))
            {
                continue;
            }

            await body().ConfigureAwait(false);
            Console.WriteLine($"PASS: {name}");
            passed++;
        }

        Console.WriteLine($"Services tests passed: {passed}.");
        return 0;
    }

    private static Func<ValueTask> Sync(Action action) => () =>
    {
        action();
        return ValueTask.CompletedTask;
    };

    private static Func<ValueTask> Async(Func<Task> action) => async () =>
    {
        await action().ConfigureAwait(false);
    };

    internal static void AssertTrue(bool value, string message)
    {
        if (!value)
        {
            throw new InvalidOperationException(message);
        }

        AssertTrue(value);
    }

    internal static void AssertTrue(bool value)
    {
        if (!value)
        {
            throw new InvalidOperationException("Expected true but received false.");
        }
    }

    internal static void AssertFalse(bool value) => AssertTrue(!value);

    internal static void AssertEqual<T>(T expected, T actual)
    {
        if (!EqualityComparer<T>.Default.Equals(expected, actual))
        {
            throw new InvalidOperationException($"Expected '{expected}' but received '{actual}'.");
        }
    }
}
